spring:
  application:
    name: hello2-service
server:
  port: 9002
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:6868/eureka/
feign:
  hystrix:
    enabled: true