spring:
  application:
    name: hello1-service
server:
  port: 9001
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:6868/eureka/
