spring:
  application:
    name: hello-service
server:
  port: 9005
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:6868/eureka/